name: Rust

defaults: 
  run: 
    shell: bash

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable

    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --all-features


  code-analysis:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: clippy/actions@0.2.1
      with:
        tool: "clippy"
    - uses: actions/checkout@v4
    - uses: rust-lang/cargo-audit-action@v0.5.0
      with:
        mode: "report"


  generate-changelog:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: github/changelog-generator@v1.11.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        path: ./CHANGELOG.md
